# Generated by Django 5.2.6 on 2025-09-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('established', models.DateField(blank=True, null=True)),
                ('site_type', models.CharField(choices=[('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('MIXED', 'Mixed')], default='CULTURAL', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='heritage_images/')),
                ('rating', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeritageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('details', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='heritage.heritagesite')),
            ],
        ),
    ]
