# Generated by Django 5.2.6 on 2025-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_alter_heritagesite_established'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritagesite',
            name='established',
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='established_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of establishment', null=True),
        ),
    ]
