# Generated by Django 5.2.6 on 2025-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_remove_heritagesite_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
