# Generated by Django 5.2.6 on 2025-09-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0004_alter_heritageevent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='architect',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='built',
            field=models.CharField(blank=True, help_text='e.g. 1631-1653', max_length=50),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='conservation_preservation_quality',
            field=models.PositiveIntegerField(blank=True, help_text='Percent 0-100', null=True),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='conservation_structural_integrity',
            field=models.PositiveIntegerField(blank=True, help_text='Percent 0-100', null=True),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='site_type',
            field=models.CharField(choices=[('NATURAL HERITAGE', 'Natural Heritage'), ('ARCHEAOLOGICAL SITE', 'Archaeological Site'), ('TEMPLE', 'Temple'), ('MONUMENT', 'Monument'), ('FORT', 'Fort'), ('PALACE', 'Palace')], max_length=30),
        ),
        migrations.CreateModel(
            name='HeritageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='heritage_resources/')),
                ('filetype', models.CharField(choices=[('PDF', 'PDF'), ('ZIP', 'ZIP')], default='PDF', max_length=10)),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('access', models.CharField(default='Public', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='heritage.heritagesite')),
            ],
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='heritage_sites', to='heritage.heritagetag'),
        ),
    ]
