# Generated by Django 5.2.6 on 2025-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_heritagetag_heritagesite_architect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='visitor_best_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='visitor_duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='visitor_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='visitor_timings',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
