# Generated by Django 5.2.6 on 2025-09-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_heritagesite_post_image_post_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_question',
        ),
    ]
