# Generated by Django 5.2.6 on 2025-09-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_comment_is_approved_remove_comment_is_flagged_and_more'),
        ('heritage', '0004_alter_heritageevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='heritage.heritagesite'),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='heritage.heritagesite'),
        ),
        migrations.DeleteModel(
            name='HeritageSite',
        ),
    ]
