# Generated by Django 5.2.6 on 2025-09-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_userbadge_site_alter_post_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vote_score',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
